### ISSUE TITLE
Missing fields on generated notification topics

### ISSUE THREAD

**Issue by stsmdt** [purecloudlabs/platform-client-sdk-common#271]
Hi,

it seems, that on some generated notification topics there are missing fields. For example `eventTime` in `Edgemetricstopicedgemetrics` struct in generated [platform-client-sdk-go](https://github.com/MyPureCloud/platform-client-sdk-go).

Compare for example [Edgemetricstopicedgemetrics](https://github.com/MyPureCloud/platform-client-sdk-go/blob/master/platformclientv2/edgemetricstopicedgemetrics.go#L10-L38) with [Edgemetrics](https://github.com/MyPureCloud/platform-client-sdk-go/blob/master/platformclientv2/edgemetrics.go#L11-L43).

Same for [Trunkmetricstopictrunkmetrics](https://github.com/MyPureCloud/platform-client-sdk-go/blob/master/platformclientv2/trunkmetricstopictrunkmetrics.go#L10-L22) and [Trunkmetrics](https://github.com/MyPureCloud/platform-client-sdk-go/blob/master/platformclientv2/trunkmetrics.go#L11-L31).

**Comment by ronanwatkins** [comment]
Hi Steffen,

It appears that `eventTime` has the swagger type `any` in the topic definition and a `datetime` type in the API definition and our codegen process ignores `any` types. I've taken a look at our other SDKs and this behaviour is consistent with them.
I'll need to find the source of this problem and fix it for all affected SDKs

**Comment by ronanwatkins** [comment]
Hi @Brombeersaft,

We are currently updating our codegen tooling to an up to date version. This problem is one of the issues that we are going to tackle and release when the update is complete.
I can't give a definite time frame but it will be out in the next few weeks.

**Comment by ronanwatkins** [comment]
Hi @Brombeersaft,

We have released v71.0.0 with the fix for this issue.
